kind: pipeline
name: default

steps:
- name: test
  image: hanami/ruby-2.6
  volumes:
  - name: cache
  - path: /drone/src
  commands:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake

volumes:
- name: cache
  temp: {}
