kind: pipeline
name: ruby-2-6
group: build

steps:
- name: install
  image: ruby:2.6.3
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ruby -v
  - gem install bundler
  - bundle install --jobs=3 --retry=3

- name: unit
  image: ruby:2.6.3
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - COVERAGE=true bundle exec rake spec:unit

- name: isolation
  image: ruby:2.6.3
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ./script/test isolation

- name: quality
  image: ruby:2.6.3
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - bundle exec rubocop

volumes:
- name: bundle
  temp: {}

---
kind: pipeline
name: ruby-2-5
group: build

steps:
- name: install
  image: ruby:2.5.3
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ruby -v
  - gem install bundler
  - bundle install --jobs=3 --retry=3

- name: unit
  image: ruby:2.5.3
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - COVERAGE=true bundle exec rake spec:unit

- name: isolation
  image: ruby:2.5.3
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ./script/test isolation

- name: quality
  image: ruby:2.5.3
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - bundle exec rubocop

volumes:
- name: bundle
  temp: {}

---
kind: pipeline
name: ruby-2-4
group: build

steps:
- name: install
  image: ruby:2.4.5
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ruby -v
  - gem install bundler
  - bundle install --jobs=3 --retry=3

- name: unit
  image: ruby:2.4.5
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - COVERAGE=true bundle exec rake spec:unit

- name: isolation
  image: ruby:2.4.5
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ./script/test isolation

- name: quality
  image: ruby:2.4.5
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - bundle exec rubocop

volumes:
- name: bundle
  temp: {}

---
kind: pipeline
name: ruby-2-3
group: build

steps:
- name: install
  image: ruby:2.3.8
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ruby -v
  - gem install bundler
  - bundle install --jobs=3 --retry=3

- name: unit
  image: ruby:2.3.8
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - COVERAGE=true bundle exec rake spec:unit

- name: isolation
  image: ruby:2.3.8
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ./script/test isolation

- name: quality
  image: ruby:2.3.8
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - bundle exec rubocop

volumes:
- name: bundle
  temp: {}

---
kind: pipeline
name: jruby-9-2
group: build

steps:
- name: install
  image: jruby:9.2.7.0
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ruby -v
  - gem install bundler
  - bundle install --jobs=3 --retry=3

- name: unit
  image: jruby:9.2.7.0
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - COVERAGE=true bundle exec rake spec:unit

- name: isolation
  image: jruby:9.2.7.0
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ./script/test isolation
  err_ignore: true

- name: quality
  image: jruby:9.2.7.0
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - bundle exec rubocop

volumes:
- name: bundle
  temp: {}

---
kind: pipeline
name: jruby-9-1
group: build

steps:
- name: install
  image: jruby:9.1.17.0
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ruby -v
  - gem install bundler
  - bundle install --jobs=3 --retry=3

- name: unit
  image: jruby:9.1.17.0
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - COVERAGE=true bundle exec rake spec:unit

- name: isolation
  image: jruby:9.1.17.0
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - ./script/test isolation

- name: quality
  image: jruby:9.1.17.0
  volumes:
  - name: bundle
    path: /usr/local/bundle
  commands:
  - bundle exec rubocop

volumes:
- name: bundle
  temp: {}
