# Please keep AllCops, Bundler, Style, Metrics groups and then order cops
# alphabetically
inherit_from:
  - https://raw.githubusercontent.com/hanami/devtools/aa9bf20052bdeab1de1763de7013f70c963427c5/.rubocop-unstable.yml
Naming/HeredocDelimiterNaming:
  Exclude:
    - "spec/**/*"
Naming/MethodName:
  Exclude:
    - "lib/hanami/utils/kernel.rb"
Layout/HashAlignment:
  Enabled: false
Layout/LineLength:
  Exclude:
    - "lib/hanami/utils/escape.rb"
    - "spec/**/*"
Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*"
Style/CommentedKeyword:
  Exclude:
    - "spec/**/*"
Style/DateTime:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/FormatStringToken:
  Exclude:
    - "spec/**/*"
Style/OptionalBooleanParameter:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/RescueStandardError:
  Exclude:
    - "spec/**/*"
