# Please keep AllCops, Bundler, Style, Metrics groups and then order cops
# alphabetically
inherit_from:
  - https://raw.githubusercontent.com/hanami/devtools/master/.rubocop-unstable.yml
Naming/HeredocDelimiterNaming:
  Exclude:
    - "spec/**/*"
Naming/MethodName:
  Exclude:
    - "lib/hanami/utils/kernel.rb"
Layout/AlignHash:
  Enabled: false
Style/CommentedKeyword:
  Exclude:
    - "spec/**/*"
Style/DateTime:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/FormatStringToken:
  Exclude:
    - "spec/**/*"
Style/MethodMissingSuper:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/RescueStandardError:
  Exclude:
    - "spec/**/*"
