# Please keep AllCops, Bundler, Style, Metrics groups and then order cops
# alphabetically
inherit_from:
  - https://raw.githubusercontent.com/hanami/devtools/5b29f678fd2a95372b3619967859f8936028276e/.rubocop-unstable.yml
Naming/HeredocDelimiterNaming:
  Exclude:
    - "spec/**/*"
Naming/MethodName:
  Exclude:
    - "lib/hanami/utils/kernel.rb"
Layout/HashAlignment:
  Enabled: false
Layout/LineLength:
  Exclude:
    - "lib/hanami/utils/escape.rb"
    - "spec/**/*"
Lint/ConstantDefinitionInBlock:
  Exclude:
    - "spec/**/*"
Lint/MissingSuper:
  Enabled: false
Style/CommentedKeyword:
  Exclude:
    - "spec/**/*"
Style/DateTime:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/FormatStringToken:
  Exclude:
    - "spec/**/*"
Style/OptionalBooleanParameter:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/RescueStandardError:
  Exclude:
    - "spec/**/*"
